
[functions.set-custom-claims]
enabled = true
verify_jwt = true
import_map = "./functions/set-custom-claims/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/set-custom-claims/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/set-custom-claims/*.html" ]
