'use client';

import React, { useMemo, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { 
  Sparkles, 
  Send, 
  Bot, 
  User, 
  Loader2, 
  Cog, 
  Server, 
  FileDown, 
  Pilcrow, 
  Compass, 
  Fingerprint, 
  Zap, 
  Activity 
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import remarkGfm from 'remark-gfm';
import { useCopilot, type CoreMessage } from '@/context/CopilotContext'; 
import { useUserProfile } from '@/hooks/useUserProfile';

// Intersection type to ensure messages have a keyable ID
type MessageWithId = CoreMessage & { id: string };

/**
 * Utility: Handles the physical download of base64 data generated by the AI
 */
const downloadFileFromBase64 = (fileName: string, mimeType: string, content: string): void => {
  try {
    const link = document.body.appendChild(document.createElement('a'));
    link.href = `data:${mimeType};base64,${content}`;
    link.download = fileName;
    link.click();
    document.body.removeChild(link);
    toast.success(`Forensic Report Exported: ${fileName}`);
  } catch (error) {
    toast.error("Neural Export Failed: Stream corruption detected.");
    console.error("Download Error:", error);
  }
};

/**
 * Component: Visualizes the AI's autonomous reasoning and tool execution
 */
const AgentStep = ({ data }: { data: any }): React.ReactNode => {
    if (!data) return null;

    try {
      // Logic for specialized UI actions (Navigate, Download, Draft)
      const outputData = data.output ? (typeof data.output === 'string' ? JSON.parse(data.output) : data.output) : {};

      if (outputData.action === "navigate") {
        return (
          <div className="text-xs text-sky-500 ml-11 my-2 p-3 border rounded-md bg-sky-500/10 border-sky-500/20 animate-pulse">
            <div className="flex items-center gap-2">
              <Compass className="h-4 w-4 flex-shrink-0" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-sky-600">Autonomous Navigation</p>
                <p className="font-mono text-[10px]">Destination: {outputData.payload?.url}</p>
              </div>
            </div>
          </div>
        );
      }
      
      if (outputData.action === "download_file") {
        return (
          <div className="text-xs text-emerald-500 ml-11 my-2 p-3 border rounded-md bg-emerald-500/10 border-emerald-500/20">
            <div className="flex items-center gap-2">
              <FileDown className="h-4 w-4 flex-shrink-0" />
              <div>
                <p className="font-bold uppercase tracking-tighter">Data Extraction Complete</p>
                <p className="text-[10px]">Buffer prepared for {outputData.payload?.fileName}</p>
              </div>
            </div>
          </div>
        );
      }

      if (outputData.action === "present_draft") {
        return (
          <div className="text-xs text-fuchsia-500 ml-11 my-2 p-3 border rounded-md bg-fuchsia-500/10 border-fuchsia-500/20">
            <div className="flex items-center gap-2">
              <Pilcrow className="h-4 w-4 flex-shrink-0" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-fuchsia-600">Synthesizing Communication</p>
                <p className="text-[10px]">Forensic draft presented for review.</p>
              </div>
            </div>
          </div>
        );
      }
    } catch (e) { /* Fallback for non-JSON output */ }

    // Logic for raw tool invocation
    if (data.tool) {
        return (
          <div className="text-[10px] text-muted-foreground ml-11 my-2 p-3 border rounded-md bg-slate-50 border-dashed">
            <div className="flex items-center gap-2">
              <Cog className="h-3 w-3 animate-spin text-emerald-600" />
              <div>
                <p className="font-bold uppercase tracking-widest text-slate-600">Executing Core: {data.tool}</p>
                <p className="opacity-60 truncate max-w-[250px] font-mono">{JSON.stringify(data.toolInput)}</p>
              </div>
            </div>
          </div>
        );
    }

    // Logic for raw tool results/observations
    if (data.output && typeof data.output === 'string' && data.output.length < 1000) {
        return (
          <div className="text-[10px] text-muted-foreground ml-11 my-2 p-2 border-l-2 border-emerald-500 bg-slate-50/50 italic font-mono">
            Observation: {data.output.substring(0, 150)}...
          </div>
        );
    }

    return null;
};

/**
 * Main Component: The Autonomous Command Center
 */
export default function CopilotPanel() {
  const router = useRouter();
  const scrollRef = useRef<HTMLDivElement>(null);
  
  // Shared AI State from Context
  const { messages, input, handleInputChange, handleSubmit, isLoading, data, isReady } = useCopilot();
  
  // Business Context for Multi-Tenant Sovereignty
  const { data: userProfile } = useUserProfile();
  const businessId = (userProfile as any)?.business_id || ''; 

  // Effect: Handle real-time side effects (Navigation & Downloads) from the stream
  useEffect(() => {
    if (data && data.length > 0) {
      const lastChunk = data[data.length - 1];
      try {
        const parsedEvent = typeof lastChunk === 'string' ? JSON.parse(lastChunk) : lastChunk;
        
        if (parsedEvent.event === 'on_tool_end' && parsedEvent.data?.output) {
          const toolOutput = typeof parsedEvent.data.output === 'string' ? JSON.parse(parsedEvent.data.output) : parsedEvent.data.output;
          
          if (toolOutput.action === "navigate" && toolOutput.payload?.url) {
            toast.info(`Aura: Redirecting to ${toolOutput.payload.url}`);
            router.push(toolOutput.payload.url);
          }
          if (toolOutput.action === "download_file" && toolOutput.payload?.fileName) {
            const { fileName, mimeType, content } = toolOutput.payload;
            downloadFileFromBase64(fileName, mimeType, content);
          }
        }
      } catch (e) { /* Raw text chunk - skip parsing */ }
    }
  }, [data, router]);
  
  // Auto-scroll logic
  useEffect(() => {
    if (scrollRef.current) {
        scrollRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, data, isLoading]);

  // Memo: Process agent steps for the UI
  const memoizedAgentSteps = useMemo(() => {
    if (!data || !Array.isArray(data)) return [];
    return data.map((chunk, i) => {
      try {
        const parsed = typeof chunk === 'string' ? JSON.parse(chunk) : chunk;
        if (parsed.event === 'on_chat_model_stream' || parsed.event === 'on_agent_finish') return null;
        return <AgentStep key={`step-${i}-${parsed.event}`} data={parsed.data} />;
      } catch (e) { return null; }
    }).filter(Boolean);
  }, [data]);

  // UI State calculations
  const streamingMessage = isLoading && messages.length > 0 ? (messages[messages.length - 1] as CoreMessage) : null;
  const renderedMessages = streamingMessage ? messages.slice(0, -1) : messages;

  // NEURAL UNLOCK: Allow typing if we have a businessId
  const canSend = !isLoading && businessId && (input || '').trim().length > 0;
  const isInputDisabled = !businessId || isLoading;
  
  return (
    <div className="h-full w-full flex flex-col bg-white overflow-hidden border-l shadow-2xl">
      {/* Forensic Branding Header */}
      <header className="p-6 border-b bg-slate-950 text-white flex flex-col gap-1 shrink-0 shadow-lg">
        <div className="flex items-center justify-between">
            <h2 className="text-lg font-black flex items-center gap-2 uppercase tracking-tighter italic text-emerald-400">
                <Fingerprint className="h-5 w-5 animate-pulse"/> Aura Intelligence
            </h2>
            <Badge className="bg-emerald-600 text-[8px] border-none px-2 py-0.5">v10.5 PRO</Badge>
        </div>
        <p className="text-[10px] text-slate-400 font-mono uppercase tracking-widest">Autonomous Forensic Co-Pilot</p>
      </header>
      
      {/* Neural Link Feed */}
      <ScrollArea className="flex-grow p-4 bg-slate-50/30">
        <div className="space-y-6">
            {messages.length === 0 && (
                <div className="py-20 text-center opacity-20 grayscale transition-all duration-1000">
                    <Bot size={64} className="mx-auto mb-4 animate-bounce text-slate-900" />
                    <p className="text-xs font-black uppercase tracking-[0.4em] text-slate-900">Awaiting Forensic Command</p>
                </div>
            )}

            {/* Rendered Past Messages */}
            {(renderedMessages as MessageWithId[]).map((m) => ( 
              <div key={m.id} className={cn('flex items-start gap-3', m.role === 'user' ? 'justify-end' : 'justify-start')}>
                {m.role === 'assistant' && (
                   <div className="w-9 h-9 rounded-xl bg-slate-900 flex items-center justify-center shadow-lg shrink-0 border border-emerald-500/20">
                      <Zap className="h-5 w-5 text-emerald-400 fill-current" />
                   </div>
                )}
                <div className={cn(
                    'rounded-2xl p-4 max-w-[85%] text-sm shadow-sm border transition-all',
                    m.role === 'user' 
                        ? 'bg-primary text-white border-primary rounded-tr-none' 
                        : 'bg-white text-slate-800 border-slate-100 rounded-tl-none'
                )}>
                  <ReactMarkdown remarkPlugins={[remarkGfm]} className="prose prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:text-emerald-400">
                    {typeof m.content === 'string' ? m.content : JSON.stringify(m.content)}
                  </ReactMarkdown>
                </div>
                {m.role === 'user' && (
                  <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center border shrink-0">
                    <User className="h-5 w-5 text-slate-400" />
                  </div>
                )}
              </div>
            ))}
            
            {/* Real-time Thought Process (Cog Wheels) */}
            {isLoading && memoizedAgentSteps}

            {/* Current Active Stream */}
            {isLoading && streamingMessage && (
                <div className="flex items-start gap-3">
                    <div className="w-9 h-9 rounded-xl bg-slate-900 flex items-center justify-center shadow-lg shrink-0 border border-emerald-500/20">
                        <Zap className="h-5 w-5 text-emerald-400 fill-current" />
                    </div>
                    <div className="rounded-2xl p-4 max-w-[85%] text-sm shadow-sm border bg-white text-slate-800 border-slate-100 rounded-tl-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]} className="prose prose-sm max-w-none">
                            {typeof streamingMessage.content === 'string' ? streamingMessage.content : JSON.stringify(streamingMessage.content)}
                        </ReactMarkdown>
                        <div className="flex items-center gap-2 mt-2 text-[10px] font-black text-emerald-600 uppercase tracking-widest animate-pulse">
                            <Loader2 className="h-3 w-3 animate-spin" /> Aura is processing...
                        </div>
                    </div>
                </div>
            )}
            
            <div ref={scrollRef} className="h-4" />
        </div>
      </ScrollArea>
      
      {/* Command Input Area */}
      <div className="p-4 border-t bg-white shrink-0">
        <form 
          onSubmit={(e) => {
            e.preventDefault();
            if (canSend) handleSubmit(e);
          }} 
          className="flex items-center gap-2"
        >
          <Input 
            value={input || ''} 
            onChange={handleInputChange} 
            placeholder={isInputDisabled ? "Neural Link Initializing..." : "Ask Aura to audit anything..."} 
            disabled={isInputDisabled}
            className="h-12 rounded-xl bg-slate-50 border-none shadow-inner focus-visible:ring-emerald-500"
          />
          <Button 
            type="submit" 
            size="icon" 
            disabled={!canSend} 
            className="h-12 w-12 rounded-xl shadow-xl bg-slate-950 hover:bg-slate-800 transition-all shrink-0"
          >
            {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-5 w-5" />}
          </Button>
        </form>

        {/* Verification Badge for the 11 Industries */}
        <div className="flex justify-between items-center mt-3 px-1">
            <div className="flex items-center gap-2 text-[9px] uppercase tracking-tighter text-muted-foreground font-bold">
                <Activity className="h-3 w-3 text-emerald-500" />
                Neural Link: <span className="font-mono text-emerald-600">{businessId ? businessId.slice(0, 12) : 'OFFLINE'}</span>
            </div>
            <div className="text-[9px] uppercase tracking-tighter font-bold text-slate-300">
                Isolated Forensic Context
            </div>
        </div>
      </div>
    </div>
  );
}