'use client';

/**
 * --- BBU1 SOVEREIGN COPILOT PANEL ---
 * The primary interface for the Autonomous Forensic Co-Pilot.
 * Orchestrates high-density message streams, autonomous UI side-effects,
 * and the rendering of the C-Suite Boardroom.
 * 
 * Capability: Multi-Agent Awareness, Real-time Visual Handshaking.
 * Integrity Grade: OMEGA-ULTIMATUM (Forensic Ready).
 */

import React, { useMemo, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { 
  Sparkles, 
  Send, 
  Bot, 
  User, 
  Loader2, 
  Cog, 
  FileDown, 
  Pilcrow, 
  Compass, 
  Fingerprint, 
  Zap, 
  Activity,
  Presentation,
  ShieldCheck,
  LayoutGrid
} from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import remarkGfm from 'remark-gfm';
import { useCopilot, type CoreMessage } from '@/context/CopilotContext'; 

// ✅ SOVEREIGN LINK: Importing the visual stage we built for Aura's Council
import AuraBoardroom from '../copilot/AuraBoardroom'; 

// Intersection type to ensure messages have a keyable ID
type MessageWithId = CoreMessage & { id: string };

/**
 * Utility: Handles the physical download of base64 data generated by the AI
 */
const downloadFileFromBase64 = (fileName: string, mimeType: string, content: string): void => {
  try {
    const link = document.body.appendChild(document.createElement('a'));
    link.href = `data:${mimeType};base64,${content}`;
    link.download = fileName;
    link.click();
    document.body.removeChild(link);
    toast.success(`Forensic Report Exported: ${fileName}`);
  } catch (error) {
    toast.error("Neural Export Failed: Stream corruption detected.");
    console.error("Download Error:", error);
  }
};

/**
 * Component: Visualizes the AI's autonomous reasoning and tool execution
 * UPGRADED: Supports Boardroom Initialization and Safety Protocol badges.
 */
const AgentStep = ({ data }: { data: any }): React.ReactNode => {
    if (!data) return null;

    try {
      // Logic for specialized UI actions (Navigate, Download, Draft, Boardroom)
      const outputData = data.output ? (typeof data.output === 'string' ? JSON.parse(data.output) : data.output) : {};

      if (outputData.action === "navigate") {
        return (
          <div className="text-xs text-sky-500 ml-11 my-2 p-3 border rounded-xl bg-sky-500/5 border-sky-500/20 animate-in fade-in slide-in-from-left-2">
            <div className="flex items-center gap-2">
              <Compass className="h-4 w-4 flex-shrink-0 animate-spin-slow" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-sky-600">Sovereign Navigation</p>
                <p className="font-mono text-[10px] opacity-70">Path: {outputData.payload?.url}</p>
              </div>
            </div>
          </div>
        );
      }
      
      if (outputData.action === "download_file") {
        return (
          <div className="text-xs text-emerald-500 ml-11 my-2 p-3 border rounded-xl bg-emerald-500/5 border-emerald-500/20 animate-in fade-in slide-in-from-left-2">
            <div className="flex items-center gap-2">
              <FileDown className="h-4 w-4 flex-shrink-0" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-emerald-600">Forensic Buffer Ready</p>
                <p className="text-[10px] opacity-70">Buffer: {outputData.payload?.fileName}</p>
              </div>
            </div>
          </div>
        );
      }

      if (outputData.action === "prepare_boardroom_presentation") {
        return (
          <div className="text-xs text-blue-500 ml-11 my-2 p-3 border rounded-xl bg-blue-500/5 border-blue-500/20 animate-in fade-in slide-in-from-left-2">
            <div className="flex items-center gap-2">
              <Presentation className="h-4 w-4 flex-shrink-0 text-blue-600" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-blue-700">Boardroom Visuals Initialized</p>
                <p className="text-[10px] opacity-70 italic">Aura is preparing the stage for Director review.</p>
              </div>
            </div>
          </div>
        );
      }

      if (outputData.action === "request_confirmation") {
        return (
          <div className="text-xs text-amber-500 ml-11 my-2 p-3 border rounded-xl bg-amber-500/5 border-amber-500/20 animate-in fade-in slide-in-from-left-2">
            <div className="flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 flex-shrink-0" />
              <div>
                <p className="font-bold uppercase tracking-tighter text-amber-600">Aura Safety Protocol</p>
                <p className="text-[10px] opacity-70 font-mono">Status: Awaiting Forensic Confirmation</p>
              </div>
            </div>
          </div>
        );
      }
    } catch (e) { /* Raw text chunk - skip */ }

    // Logic for raw tool invocation pulse
    if (data.tool) {
        return (
          <div className="text-[10px] text-muted-foreground ml-11 my-2 p-3 border rounded-xl bg-slate-50 border-dashed animate-pulse">
            <div className="flex items-center gap-2">
              <Cog className="h-3 w-3 animate-spin text-emerald-600" />
              <div>
                <p className="font-bold uppercase tracking-widest text-slate-600">Executive Council Acting: {data.tool}</p>
                <p className="opacity-50 truncate max-w-[250px] font-mono">{JSON.stringify(data.toolInput)}</p>
              </div>
            </div>
          </div>
        );
    }

    return null;
};

/**
 * Main Component: The Sovereign Autonomous Command Center
 */
export default function CopilotPanel() {
  const router = useRouter();
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // --- OMEGA UPGRADE: BOARDROOM STATE ---
  const [boardroomData, setBoardroomData] = useState<any | null>(null);
  
  // Shared AI Context from BBU1 Kernel
  const { 
    messages, 
    input, 
    handleInputChange, 
    handleSubmit, 
    isLoading, 
    data, 
    isReady, 
    businessId, 
    userId 
  } = useCopilot();
  
  /**
   * NEURAL SIDE-EFFECT MONITOR
   * Monitors the AI stream for executive system commands (Navigation, Boardroom, Downloads)
   */
  useEffect(() => {
    if (data && data.length > 0) {
      const lastChunk = data[data.length - 1];
      try {
        const parsedEvent = typeof lastChunk === 'string' ? JSON.parse(lastChunk) : lastChunk;
        
        // Handlers for 'on_tool_end' (Successful forensic completion)
        if (parsedEvent.event === 'on_tool_end' && parsedEvent.data?.output) {
          const toolOutput = typeof parsedEvent.data.output === 'string' 
            ? JSON.parse(parsedEvent.data.output) 
            : parsedEvent.data.output;
          
          // 1. Navigation Executive
          if (toolOutput.action === "navigate" && toolOutput.payload?.url) {
            toast.info(`Aura: Navigating to ${toolOutput.payload.url}`);
            router.push(toolOutput.payload.url);
          }

          // 2. Download Executive
          if (toolOutput.action === "download_file" && toolOutput.payload?.fileName) {
            const { fileName, mimeType, content } = toolOutput.payload;
            downloadFileFromBase64(fileName, mimeType, content);
          }

          // 3. BOARDROOM EXECUTIVE: Opens the visual stage
          if (toolOutput.action === "prepare_boardroom_presentation") {
            setBoardroomData(toolOutput.payload);
            toast.success("Presentation Synchronized", {
                description: "Aura is ready to present her findings."
            });
          }
        }
      } catch (e) { /* Raw text processing */ }
    }
  }, [data, router]);
  
  // Auto-scroll logic
  useEffect(() => {
    if (scrollRef.current) {
        scrollRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, data, isLoading]);

  /**
   * FOCUS PROTOCOL
   * Forces focus to the input box once the multi-tenant context is active.
   */
  useEffect(() => {
    if (isReady && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isReady]);

  // Memo: Render the autonomous thought sequence
  const memoizedAgentSteps = useMemo(() => {
    if (!data || !Array.isArray(data)) return [];
    return data.map((chunk, i) => {
      try {
        const parsed = typeof chunk === 'string' ? JSON.parse(chunk) : chunk;
        if (parsed.event === 'on_chat_model_stream' || parsed.event === 'on_agent_finish') return null;
        return <AgentStep key={`step-${i}-${parsed.event}`} data={parsed.data} />;
      } catch (e) { return null; }
    }).filter(Boolean);
  }, [data]);

  const streamingMessage = isLoading && messages.length > 0 ? (messages[messages.length - 1] as CoreMessage) : null;
  const renderedMessages = streamingMessage ? messages.slice(0, -1) : messages;

  const canSend = !isLoading && (input || '').trim().length > 0;
  
  return (
    <div className="h-full w-full flex flex-col bg-white overflow-hidden border-l shadow-2xl relative">
      
      {/* 🚀 OMEGA LAYER: The Boardroom stage (Renders on top of panel) */}
      <AnimatePresence>
        {boardroomData && (
          <AuraBoardroom 
            presenter={boardroomData.presenter_role}
            title={boardroomData.meeting_title}
            slides={boardroomData.slides}
            onClose={() => setBoardroomData(null)}
          />
        )}
      </AnimatePresence>

      {/* 1. EXECUTIVE HEADER */}
      <header className="p-6 border-b bg-slate-950 text-white flex flex-col gap-1 shrink-0 shadow-lg relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
            <Fingerprint size={80} className="text-emerald-500" />
        </div>
        <div className="flex items-center justify-between relative z-10">
            <h2 className="text-lg font-black flex items-center gap-2 uppercase tracking-tighter italic text-emerald-400">
                <Zap className="h-5 w-5 fill-emerald-400 animate-pulse"/> Aura Intelligence
            </h2>
            <div className="flex items-center gap-2">
               {isReady && <Badge className="bg-emerald-600 text-[8px] border-none px-2 py-0.5 animate-in fade-in">ENCRYPTED</Badge>}
               <Badge className="bg-slate-800 text-slate-400 text-[8px] border-none px-2 py-0.5">v10.8 PRO</Badge>
            </div>
        </div>
        <p className="text-[10px] text-slate-400 font-mono uppercase tracking-widest relative z-10">Autonomous C-Suite Engine</p>
      </header>
      
      {/* 2. NEURAL LINK FEED */}
      <ScrollArea className="flex-grow p-4 bg-slate-50/30">
        <div className="space-y-6 max-w-2xl mx-auto">
            {!isReady && messages.length === 0 && (
                <div className="py-32 text-center animate-in fade-in duration-700">
                    <Loader2 className="h-10 w-10 animate-spin mx-auto text-emerald-500 mb-4" />
                    <p className="text-xs font-black uppercase tracking-[0.4em] text-slate-400">Handshaking Sovereign ID...</p>
                </div>
            )}

            {isReady && messages.length === 0 && (
                <div className="py-20 text-center opacity-20 grayscale transition-all duration-1000">
                    <Bot size={64} className="mx-auto mb-4 animate-bounce text-slate-900" />
                    <p className="text-xs font-black uppercase tracking-[0.4em] text-slate-900">Awaiting Executive Directive</p>
                </div>
            )}

            {/* Historical Transcript */}
            {(renderedMessages as MessageWithId[]).map((m) => ( 
              <div key={m.id} className={cn('flex items-start gap-3', m.role === 'user' ? 'justify-end' : 'justify-start')}>
                {m.role === 'assistant' && (
                   <div className="w-9 h-9 rounded-xl bg-slate-900 flex items-center justify-center shadow-lg shrink-0 border border-emerald-500/20">
                      <Sparkles className="h-5 w-5 text-emerald-400" />
                   </div>
                )}
                <div className={cn(
                    'rounded-2xl p-4 max-w-[85%] text-sm shadow-sm border transition-all leading-relaxed',
                    m.role === 'user' 
                        ? 'bg-primary text-white border-primary rounded-tr-none' 
                        : 'bg-white text-slate-800 border-slate-100 rounded-tl-none shadow-inner'
                )}>
                  <ReactMarkdown remarkPlugins={[remarkGfm]} className="prose prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:text-emerald-400">
                    {typeof m.content === 'string' ? m.content : JSON.stringify(m.content)}
                  </ReactMarkdown>
                </div>
                {m.role === 'user' && (
                  <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center border shrink-0">
                    <User className="h-5 w-5 text-slate-400" />
                  </div>
                )}
              </div>
            ))}
            
            {/* Real-time Thought Monitor */}
            {isLoading && memoizedAgentSteps}

            {/* Active Cloud Stream */}
            {isLoading && streamingMessage && (
                <div className="flex items-start gap-3 animate-in slide-in-from-bottom-2">
                    <div className="w-9 h-9 rounded-xl bg-slate-900 flex items-center justify-center shadow-lg shrink-0 border border-emerald-500/20">
                        <Zap className="h-5 w-5 text-emerald-400 fill-current" />
                    </div>
                    <div className="rounded-2xl p-4 max-w-[85%] text-sm shadow-sm border bg-white text-slate-800 border-slate-100 rounded-tl-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]} className="prose prose-sm max-w-none">
                            {typeof streamingMessage.content === 'string' ? streamingMessage.content : JSON.stringify(streamingMessage.content)}
                        </ReactMarkdown>
                        <div className="flex items-center gap-2 mt-3 text-[10px] font-black text-emerald-600 uppercase tracking-widest animate-pulse">
                            <Loader2 className="h-3 w-3 animate-spin" /> Aura is auditing sector state...
                        </div>
                    </div>
                </div>
            )}
            
            <div ref={scrollRef} className="h-8" />
        </div>
      </ScrollArea>
      
      {/* 3. EXECUTIVE COMMAND INPUT */}
      <footer className="p-6 border-t bg-white shrink-0 shadow-[0_-10px_40px_rgba(0,0,0,0.02)] relative z-20">
        <form 
          onSubmit={(e) => {
            e.preventDefault();
            handleSubmit(e);
          }} 
          className="flex items-center gap-3"
        >
          <Input 
            ref={inputRef}
            value={input || ''} 
            onChange={handleInputChange} 
            placeholder={!isReady ? "Sovereign Link Syncing..." : "Command Aura-[Agent] to audit..."} 
            disabled={isLoading}
            className="h-14 rounded-2xl bg-slate-50 border-none shadow-inner focus-visible:ring-2 focus-visible:ring-emerald-500 transition-all text-base px-6 font-medium"
          />
          <Button 
            type="submit" 
            size="icon" 
            disabled={!canSend} 
            className={cn(
                "h-14 w-14 rounded-2xl shadow-xl transition-all shrink-0 active:scale-95",
                canSend ? "bg-slate-950 hover:bg-slate-800 scale-100" : "bg-slate-100 grayscale opacity-40"
            )}
          >
            {isLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : <Send className="h-6 w-6" />}
          </Button>
        </form>

        {/* 4. NEURAL HANDSHAKE STATUS */}
        <div className="flex justify-between items-end mt-4 px-1 pt-4 border-t border-slate-50">
            <div className="flex flex-col gap-1.5">
                <div className="flex items-center gap-2 text-[9px] uppercase tracking-tighter text-muted-foreground font-bold">
                    <Activity className="h-3 w-3 text-emerald-500" />
                    Vault Link: <span className="font-mono text-emerald-600 bg-emerald-50 px-1 rounded">{businessId ? businessId.slice(0, 18) : 'IDENTIFYING...'}</span>
                </div>
                <div className="flex items-center gap-2 text-[9px] uppercase tracking-tighter text-muted-foreground font-bold">
                    <Fingerprint className="h-3 w-3 text-sky-500" />
                    Forensic ID: <span className="font-mono text-sky-600 bg-sky-50 px-1 rounded">{userId ? userId.slice(0, 18) : 'VERIFYING...'}</span>
                </div>
            </div>
            <div className="text-[8px] uppercase tracking-tighter font-black text-slate-300 text-right leading-tight">
                Isolated Executive Vault<br/>11 Global Sectors Online
            </div>
        </div>
      </footer>
    </div>
  );
}

/**
 * STATUS: Copilot Panel High-Availability Link Established.
 * VERSION: v10.8 Sovereign Edition.
 * JURISDICTION: BBU1 Global C-Suite.
 */