'use client';

import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { createClient } from '@/lib/supabase/client';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { 
    TrendingUp, FlaskConical, AlertTriangle, FileDown, 
    ShieldCheck, Calendar, Filter, ChevronDown, 
    Printer, Loader2, Database, Activity, User, Building2, Fingerprint
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { 
    Popover, PopoverContent, PopoverTrigger 
} from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { format, startOfMonth, endOfMonth, subDays } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';

// --- IDENTITY & CONTEXT IMPORTS ---
import { useTenant } from '@/hooks/useTenant';
import { useUserProfile } from '@/hooks/useUserProfile';

const supabase = createClient();

export default function ManufacturingReportCenter() {
    const { data: tenant } = useTenant();
    const { data: profile } = useUserProfile();

    // --- CONTEXT RESOLUTION ---
    const businessName = tenant?.business_display_name || "Enterprise Unit";
    const operatorName = profile?.full_name || "Authorized User";
    const currencyCode = tenant?.reporting_currency || "UGX";

    // --- DATE MANAGEMENT ---
    const [dateRange, setDateRange] = useState({
        from: format(startOfMonth(new Date()), 'yyyy-MM-dd'),
        to: format(new Date(), 'yyyy-MM-dd')
    });

    // --- DATA FETCHING ---
    const { data: auditData, isLoading } = useQuery({
        queryKey: ['mfg_audit_report', dateRange, tenant?.id],
        queryFn: async () => {
            if (!tenant?.id) return [];
            const { data, error } = await supabase
                .from('view_manufacturing_audit_master')
                .select('*')
                .eq('tenant_id', tenant.id) 
                .gte('production_date', dateRange.from)
                .lte('production_date', dateRange.to)
                .order('production_date', { ascending: false });
            
            if (error) throw error;
            return data || [];
        },
        enabled: !!tenant?.id
    });

    // --- ANALYTICS CALCULATIONS ---
    const summary = useMemo(() => {
        if (!auditData) return { totalValue: 0, totalWastage: 0, avgEfficiency: 0, vatInput: 0 };
        const totalValue = auditData.reduce((s, i) => s + i.total_batch_expenditure, 0);
        const totalWastage = auditData.reduce((s, i) => s + i.wastage, 0);
        const vatInput = auditData.reduce((s, i) => s + (i.estimated_vat_input || 0), 0);
        const efficiency = auditData.length > 0 
            ? (auditData.reduce((s, i) => s + (i.yield / i.planned_quantity), 0) / auditData.length) * 100 
            : 0;
        
        return { totalValue, totalWastage, avgEfficiency: efficiency.toFixed(1), vatInput };
    }, [auditData]);

    // --- PDF EXPORT LOGIC ---
    const exportToPDF = () => {
        if (!auditData || auditData.length === 0) {
            toast.error("Error: No data available for export.");
            return;
        }

        const doc = new jsPDF('l', 'mm', 'a4');
        const timestamp = format(new Date(), 'dd MMM yyyy, HH:mm');

        doc.setFontSize(22);
        doc.setTextColor(15, 23, 42);
        doc.text('BATCH PRODUCTION AUDIT REPORT', 14, 22);
        
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(`Business Unit: ${businessName}`, 14, 30);
        doc.text(`Generated By: ${operatorName}`, 14, 34);
        doc.text(`Date Range: ${dateRange.from} to ${dateRange.to}`, 14, 38);

        doc.setDrawColor(241, 245, 249);
        doc.setFillColor(248, 250, 252); 
        doc.rect(14, 45, 270, 18, 'FD');
        doc.setFontSize(10);
        doc.setTextColor(15, 23, 42);
        doc.setFont("helvetica", "bold");
        doc.text(`Total Production Value: ${summary.totalValue.toLocaleString()} ${currencyCode}`, 20, 56);
        doc.text(`Total Wasted Units: ${summary.totalWastage}`, 110, 56);
        doc.text(`Input VAT Estimate: ${summary.vatInput.toLocaleString()} ${currencyCode}`, 190, 56);

        autoTable(doc, {
            startY: 70,
            head: [['Batch No.', 'Product Name', 'Yield', 'Wasted', 'Cost/Unit', 'Total Cost', 'Production Date']],
            body: auditData.map(r => [
                r.batch_number,
                r.finished_product,
                r.yield,
                r.wastage,
                `${r.landed_cost_per_unit.toLocaleString()} ${currencyCode}`,
                `${r.total_batch_expenditure.toLocaleString()} ${currencyCode}`,
                format(new Date(r.production_date), 'yyyy-MM-dd')
            ]),
            styles: { fontSize: 8, cellPadding: 4 },
            headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
            alternateRowStyles: { fillColor: [252, 252, 252] },
        });

        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(7);
        doc.setTextColor(150);
        doc.text(`Exported from LITONU System Center. Timestamp: ${timestamp}`, 14, finalY);

        doc.save(`Production_Report_${businessName.replace(/\s/g, '_')}_${dateRange.from}.pdf`);
        toast.success("PDF Export Completed");
    };

    return (
        <div className="max-w-[1500px] mx-auto py-8 px-6 space-y-8 animate-in fade-in duration-500 bg-slate-50/30 min-h-screen">
            
            {/* HEADER & CONTROLS */}
            <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6 border-b border-slate-200 pb-8">
                <div className="space-y-1.5">
                    <div className="flex items-center gap-3">
                        <div className="h-10 w-10 bg-slate-900 rounded-xl flex items-center justify-center text-white shadow-md">
                            <Activity size={20} />
                        </div>
                        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Production Performance Analysis</h1>
                    </div>
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2 ml-1">
                        <ShieldCheck size={12} className="text-emerald-500" /> Active Business Unit: {businessName}
                    </p>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                    <Popover>
                        <PopoverTrigger asChild>
                            <Button variant="outline" className="h-12 border-slate-200 font-bold uppercase tracking-widest text-[10px] gap-3 px-6 shadow-sm bg-white rounded-xl hover:bg-slate-50">
                                <Calendar size={16} className="text-blue-600" />
                                {format(new Date(dateRange.from), 'MMM d')} - {format(new Date(dateRange.to), 'MMM d, yyyy')}
                                <ChevronDown size={14} className="opacity-40" />
                            </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-80 p-6 space-y-5 rounded-[2rem] shadow-2xl border-none bg-white" align="end">
                            <div className="space-y-3">
                                <label className="text-[10px] font-bold uppercase text-slate-400 tracking-widest ml-1">Quick Selection</label>
                                <div className="grid grid-cols-2 gap-2">
                                    <Button variant="ghost" size="sm" onClick={() => setDateRange({from: format(new Date(), 'yyyy-MM-dd'), to: format(new Date(), 'yyyy-MM-dd')})} className="text-[10px] font-bold uppercase">Today</Button>
                                    <Button variant="ghost" size="sm" onClick={() => setDateRange({from: format(startOfMonth(new Date()), 'yyyy-MM-dd'), to: format(new Date(), 'yyyy-MM-dd')})} className="text-[10px] font-bold uppercase text-blue-600 bg-blue-50">This Month</Button>
                                    <Button variant="ghost" size="sm" onClick={() => setDateRange({from: format(subDays(new Date(), 30), 'yyyy-MM-dd'), to: format(new Date(), 'yyyy-MM-dd')})} className="text-[10px] font-bold uppercase col-span-2">Last 30 Days</Button>
                                </div>
                            </div>
                            <div className="space-y-3 border-t pt-5">
                                <label className="text-[10px] font-bold uppercase text-slate-400 tracking-widest ml-1">Specific Dates</label>
                                <div className="grid gap-3">
                                    <Input type="date" value={dateRange.from} onChange={e => setDateRange({...dateRange, from: e.target.value})} className="h-10 text-xs font-semibold border-slate-100 bg-slate-50 rounded-lg" />
                                    <Input type="date" value={dateRange.to} onChange={e => setDateRange({...dateRange, to: e.target.value})} className="h-10 text-xs font-semibold border-slate-100 bg-slate-50 rounded-lg" />
                                </div>
                            </div>
                        </PopoverContent>
                    </Popover>

                    <Button onClick={exportToPDF} className="bg-blue-600 hover:bg-blue-700 text-white font-bold h-12 px-8 gap-3 shadow-lg rounded-xl transition-all uppercase tracking-widest text-[10px]">
                        <FileDown size={18} /> Download PDF Report
                    </Button>
                </div>
            </div>

            {/* KEY PERFORMANCE CARDS */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                <Card className="border-none shadow-xl shadow-slate-200/40 rounded-[1.5rem] bg-slate-900 text-white">
                    <CardContent className="p-6">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Total Production Value</p>
                        <div className="flex items-baseline gap-2 mt-3">
                            <p className="text-2xl font-bold tabular-nums">{summary.totalValue.toLocaleString()}</p>
                            <span className="text-[9px] font-bold text-slate-500 uppercase">{currencyCode}</span>
                        </div>
                        <div className="flex items-center gap-2 mt-4 text-emerald-400">
                            <TrendingUp size={14}/>
                            <span className="text-[9px] font-bold uppercase tracking-widest">Growth Analytics</span>
                        </div>
                    </CardContent>
                </Card>

                <Card className="border-none shadow-xl shadow-slate-200/40 rounded-[1.5rem] bg-white">
                    <CardContent className="p-6">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Total Wastage</p>
                        <p className="text-2xl font-bold mt-3 tabular-nums text-slate-900">{summary.totalWastage.toLocaleString()}</p>
                        <div className="flex items-center gap-2 mt-4 text-red-500">
                            <AlertTriangle size={14}/>
                            <span className="text-[9px] font-bold uppercase tracking-widest">Loss Identified</span>
                        </div>
                    </CardContent>
                </Card>

                <Card className="border-none shadow-xl shadow-slate-200/40 rounded-[1.5rem] bg-white">
                    <CardContent className="p-6">
                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Input VAT Total</p>
                        <div className="flex items-baseline gap-2 mt-3">
                            <p className="text-2xl font-bold tabular-nums text-slate-900">{summary.vatInput.toLocaleString()}</p>
                            <span className="text-[9px] font-bold text-slate-400 uppercase">{currencyCode}</span>
                        </div>
                        <div className="flex items-center gap-2 mt-4 text-blue-600">
                            <Database size={14}/>
                            <span className="text-[9px] font-bold uppercase tracking-widest">Tax Credit Summary</span>
                        </div>
                    </CardContent>
                </Card>

                <Card className="border-none shadow-xl shadow-slate-200/40 rounded-[1.5rem] bg-blue-600 text-white">
                    <CardContent className="p-6">
                        <p className="text-[10px] font-bold uppercase tracking-widest opacity-60">Output Accuracy</p>
                        <p className="text-2xl font-bold mt-3 tabular-nums">{summary.avgEfficiency}%</p>
                        <div className="flex items-center gap-2 mt-4">
                            <ShieldCheck size={14}/>
                            <span className="text-[9px] font-bold uppercase tracking-widest">Yield Performance</span>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* DATA LEDGER TABLE */}
            <Card className="border-none shadow-xl shadow-slate-200/40 rounded-[2rem] overflow-hidden bg-white">
                <CardHeader className="border-b border-slate-50 bg-white p-8">
                    <div className="flex justify-between items-center">
                        <div>
                           <CardTitle className="text-xl font-bold text-slate-900 uppercase">
                               Batch Production Ledger
                           </CardTitle>
                           <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mt-1">Detailed production history for selected period</p>
                        </div>
                        <div className="flex flex-col items-end">
                            <Badge variant="outline" className="bg-slate-50 text-slate-500 font-bold px-4 py-1 border-slate-100 uppercase text-[9px] tracking-widest rounded-full">Reporting Node</Badge>
                            <span className="text-[8px] font-bold text-slate-300 uppercase mt-2 tracking-widest">System synchronized</span>
                        </div>
                    </div>
                </CardHeader>
                <CardContent className="p-0">
                    <ScrollArea className="h-[550px]">
                        <Table>
                            <TableHeader className="bg-slate-50/50 backdrop-blur-md sticky top-0 z-10 border-b border-slate-100">
                                <TableRow className="hover:bg-transparent border-none">
                                    <TableHead className="font-bold text-[10px] uppercase h-16 tracking-wider px-10 text-slate-500">Batch Number</TableHead>
                                    <TableHead className="font-bold text-[10px] uppercase h-16 tracking-wider text-slate-500">Product Name</TableHead>
                                    <TableHead className="font-bold text-[10px] uppercase h-16 tracking-wider text-center text-slate-500">Yield Result</TableHead>
                                    <TableHead className="font-bold text-[10px] uppercase h-16 tracking-wider text-right text-slate-500">Cost per Unit</TableHead>
                                    <TableHead className="font-bold text-[10px] uppercase h-16 tracking-wider text-right px-10 text-slate-500">Total Production Cost</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {isLoading ? (
                                    <TableRow><TableCell colSpan={5} className="h-64 text-center">
                                        <div className="flex flex-col items-center gap-3">
                                            <Loader2 className="animate-spin h-8 w-8 text-blue-600"/>
                                            <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Loading Production Data...</span>
                                        </div>
                                    </TableCell></TableRow>
                                ) : auditData?.length === 0 ? (
                                    <TableRow><TableCell colSpan={5} className="h-64 text-center">
                                        <div className="opacity-20 flex flex-col items-center gap-3">
                                            <Database size={48} />
                                            <p className="text-xs font-bold uppercase">No records found for this period</p>
                                        </div>
                                    </TableCell></TableRow>
                                ) : auditData?.map((report: any) => (
                                    <TableRow key={report.batch_number} className="hover:bg-slate-50/50 transition-colors border-b border-slate-50">
                                        <TableCell className="font-mono text-blue-600 font-bold px-10 py-6 text-sm">{report.batch_number}</TableCell>
                                        <TableCell>
                                            <div className="font-bold text-slate-900 text-sm">{report.finished_product}</div>
                                            <div className="text-[9px] font-bold text-slate-400 uppercase mt-1">{format(new Date(report.production_date), 'dd MMMM yyyy')}</div>
                                        </TableCell>
                                        <TableCell className="text-center">
                                            <div className="text-sm font-bold text-slate-700 font-mono">{report.yield} / {report.planned_quantity}</div>
                                            <Badge variant={report.wastage > 0 ? "destructive" : "secondary"} className="text-[9px] font-bold px-3 py-0.5 mt-2 uppercase tracking-widest rounded-md border-none">
                                                {report.wastage > 0 ? `${report.wastage} Wasted` : "Planned Yield"}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <div className="text-sm font-bold text-slate-900 tabular-nums">{report.landed_cost_per_unit.toLocaleString()}</div>
                                            <span className="text-[8px] font-bold text-slate-400 uppercase">{currencyCode}</span>
                                        </TableCell>
                                        <TableCell className="text-right px-10">
                                            <div className="text-base font-bold text-blue-600 tabular-nums">{report.total_batch_expenditure.toLocaleString()}</div>
                                            <span className="text-[8px] font-bold text-slate-300 uppercase">Confirmed</span>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </ScrollArea>
                </CardContent>
                <CardFooter className="bg-slate-50/50 p-6 flex justify-between items-center border-t border-slate-100">
                    <div className="flex items-center gap-3 text-slate-400">
                        <Fingerprint size={16} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Production Ledger Sync Status: Verified</span>
                    </div>
                    <div className="flex items-center gap-3">
                         <span className="text-[10px] font-semibold text-slate-400 uppercase">Verified User: {operatorName}</span>
                         <div className="h-2 w-2 rounded-full bg-emerald-500 shadow-sm" />
                    </div>
                </CardFooter>
            </Card>

            {/* COPYRIGHT FOOTER */}
            <div className="flex justify-center items-center gap-6 py-12 opacity-30">
                <div className="h-[1px] w-24 bg-slate-200" />
                <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.5em]">
                    &copy; {new Date().getFullYear()} LITONU BUSINESS BASE UNIVERSE LTD
                </p>
                <div className="h-[1px] w-24 bg-slate-200" />
            </div>
        </div>
    );
}