'use client';

import * as React from "react";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { useQuery } from "@tanstack/react-query";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table";
import { createClient } from "@/lib/supabase/client";
import { Loader2, FileBarChart, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";

interface ReportRow { 
    id: string; 
    report_name: string; 
    period_start: string; 
    period_end: string;
    generated_at: string; 
    generated_by: string; 
    download_url: string; 
}

async function fetchReports(tenantId: string) {
  const db = createClient();
  const { data, error } = await db
    .from('sacco_reports')
    .select('*')
    .eq('tenant_id', tenantId)
    .order('generated_at', { ascending: false });
  
  if (error) throw error; 
  return data as ReportRow[];
}

export function SaccoReportsCenter({ tenantId }: { tenantId: string }) {
  const { data, isLoading } = useQuery({ 
      queryKey: ['sacco-reports', tenantId], 
      queryFn: () => fetchReports(tenantId) 
  });

  return (
    <Card className="h-full border-t-4 border-t-purple-600 shadow-sm">
      <CardHeader>
          <CardTitle className="flex items-center gap-2">
              <FileBarChart className="w-5 h-5 text-purple-600"/> Reports Center
          </CardTitle>
          <CardDescription>Download standardized financial and operational reports.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="rounded-md border">
            <Table>
            <TableHeader className="bg-slate-50">
                <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead className="text-right">Download</TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                {isLoading ? (
                    <TableRow><TableCell colSpan={5} className="h-24 text-center"><Loader2 className="animate-spin mx-auto"/></TableCell></TableRow>
                ) : !data || data.length === 0 ? (
                    <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">No reports available.</TableCell></TableRow>
                ) : (
                    data.map((r) => (
                    <TableRow key={r.id}>
                        <TableCell className="font-medium">{r.report_name}</TableCell>
                        <TableCell className="text-xs text-muted-foreground">
                            {format(new Date(r.period_start), 'MMM yyyy')}
                        </TableCell>
                        <TableCell className="text-xs text-muted-foreground">
                            {format(new Date(r.generated_at), 'PP p')}
                        </TableCell>
                        <TableCell className="text-sm">{r.generated_by}</TableCell>
                        <TableCell className="text-right">
                            <Button variant="ghost" size="sm" asChild className="text-indigo-600 hover:text-indigo-700">
                                <a href={r.download_url} target="_blank" rel="noopener noreferrer">
                                    <Download className="w-4 h-4 mr-2"/> PDF
                                </a>
                            </Button>
                        </TableCell>
                    </TableRow>
                    ))
                )}
            </TableBody>
            </Table>
        </div>
      </CardContent>
    </Card>
  );
}