'use client';

import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { createClient } from '@/lib/supabase/client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Zap, Send, Trash2, ShieldCheck, AlertCircle, ShoppingCart } from 'lucide-react';
import { toast } from 'sonner';

export default function AgenticDraftsPanel() {
  const supabase = createClient();
  const queryClient = useQueryClient();

  const { data: drafts, isLoading } = useQuery({
    queryKey: ['agenticDrafts'],
    queryFn: async () => {
      const { data } = await supabase
        .from('communication_drafts')
        .select('*')
        .eq('status', 'pending_approval')
        .order('created_at', { ascending: false });
      return data || [];
    }
  });

  const approveMutation = useMutation({
    mutationFn: async (draftId: string) => {
      // Logic: Update status to trigger the actual outbound agentic message
      const { error } = await supabase
        .from('communication_drafts')
        .update({ status: 'sent' })
        .eq('id', draftId);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Agentic Handshake Executed", {
        description: "Message dispatched to supplier via preferred channel.",
        icon: <ShieldCheck className="text-emerald-500" />
      });
      queryClient.invalidateQueries({ queryKey: ['agenticDrafts'] });
    }
  });

  if (isLoading) return <div className="h-64 animate-pulse bg-slate-50 rounded-xl" />;

  return (
    <Card className="border-emerald-200 shadow-xl overflow-hidden">
      <CardHeader className="bg-emerald-50/50 border-b">
        <div className="flex justify-between items-center">
          <div>
            <CardTitle className="text-emerald-900 flex items-center gap-2">
              <Zap size={18} className="fill-emerald-500 text-emerald-500 animate-pulse" />
              Agentic Sourcing Drafts
            </CardTitle>
            <CardDescription className="text-emerald-700/70 font-medium">
              Suggestions generated by the Autonomous Sourcing Orchestrator kernel.
            </CardDescription>
          </div>
          <Badge className="bg-emerald-600 border-none px-3">KERNEL v10.2 ACTIVE</Badge>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow className="bg-slate-50">
              <TableHead className="w-[200px]">Subject</TableHead>
              <TableHead>Draft Content</TableHead>
              <TableHead>Created</TableHead>
              <TableHead className="text-right">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {drafts?.length === 0 ? (
              <TableRow>
                <TableCell colSpan={4} className="h-32 text-center text-slate-400 italic">
                  No sourcing suggestions from agents today.
                </TableCell>
              </TableRow>
            ) : (
              drafts?.map(draft => (
                <TableRow key={draft.id} className="group hover:bg-emerald-50/30 transition-colors">
                  <TableCell className="font-bold text-slate-800 flex items-center gap-2">
                    <ShoppingCart size={14} className="text-emerald-500" />
                    {draft.subject}
                  </TableCell>
                  <TableCell className="text-xs text-slate-500 max-w-md italic">
                    "{draft.body}"
                  </TableCell>
                  <TableCell className="text-xs font-mono text-slate-400">
                    {new Date(draft.created_at!).toLocaleDateString()}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button variant="ghost" size="icon" className="text-slate-300 hover:text-red-500">
                        <Trash2 size={16} />
                      </Button>
                      <Button 
                        size="sm" 
                        onClick={() => approveMutation.mutate(draft.id)}
                        className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold h-8"
                      >
                        <Send size={14} className="mr-2" /> Approve & Send
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}